### ISSUE TITLE
Does not work in Gnome 42

### ISSUE THREAD

**Issue by Strykar** [fedeantuna/inactivity#1]
Neither on 42.1

**Comment by fedeantuna** [comment]
Please check now and let me know if it still doesn't work :)

**Comment by Strykar** [comment]
Cheers!

**Comment by Strykar** [comment]
Re-opening as a recent update appears to have broken something:
`extension.stateObj.enable is not a function`

**Comment by fedeantuna** [comment]
This is turning to be a very busy week, but I will take a look as soon as I can and update you here!

**Comment by Strykar** [comment]
@fedeantuna Any updates? No pressure :)

**Comment by fedeantuna** [comment]
yes! I did some testing and I'll be publishing the working version today, sorry for the delay

**Comment by fedeantuna** [comment]
I just published the new version, also tested on a fresh Fedora 36 installation and it's running :)

Please confirm that it works for you! (You might need to log out and in if you are upgrading)

**Comment by fedeantuna** [comment]
Closing this for now since other users have reported that this is working. If the issue continues for anyone, feel free to reopen
