### ISSUE TITLE
Would be great to get GNOME 43 support

### ISSUE THREAD

**Issue by f8ttyc8t** [fedeantuna/inactivity#2]
Currently, extension does not support GNOME 43... 

Potential (kind of) fix: Replace
`"shell-version": ["42"],`
by
`"shell-version": ["43"],`
in file 
`metadata.json`

Extension works as expected after doing so, at least on my system (Fedora 37).

Loving this extension, great idea & work!

**Comment by fedeantuna** [comment]
I'll make the change as soon as I can, thanks for reporting this!

**Comment by f8ttyc8t** [comment]
My pleasure - really enjoying this extension!

**Comment by fedeantuna** [comment]
Hey sorry that it took me so long, I uploaded a new version. Let me know if it works :) I will make a fix if it doesn't

**Comment by f8ttyc8t** [comment]
Updated, works as expected now.

Thank you for fixing it!
